/**
 * Copyright 2023 Jerónimo López Bezanilla
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.jerolba.carpet.jdbc;

import java.util.Base64;

import javax.crypto.SecretKey;

import software.amazon.awssdk.regions.Region;
import software.amazon.awssdk.services.kms.KmsClient;
import software.amazon.awssdk.services.kms.model.GenerateDataKeyRequest;
import software.amazon.awssdk.services.kms.model.GenerateDataKeyResponse;

/**
 * Manages a shared Data Encryption Key (DEK) for batch encryption operations.
 *
 * This class generates a single DEK and encrypts it once with KMS, then reuses
 * the same DEK for multiple files. This significantly reduces KMS API calls
 * while maintaining strong security (each file still gets a unique IV).
 *
 * Usage:
 * <pre>
 * try (KmsSharedKeyEncryptionContext context =
 *         new KmsSharedKeyEncryptionContext(kmsConfig)) {
 *
 *     // Export multiple files using the same DEK
 *     for (String table : tables) {
 *         context.createEncryptingOutputStream(new File(table + ".parquet"));
 *     }
 * }
 * </pre>
 */
public class KmsSharedKeyEncryptionContext implements AutoCloseable {

    private final KmsEncryptionConfig config;
    private final KmsClient kmsClient;
    private final SecretKey dataKey;
    private final byte[] encryptedDataKey;
    private volatile boolean closed = false;

    /**
     * Create a shared encryption context with a single DEK
     *
     * @param config KMS encryption configuration
     * @throws Exception if DEK generation or KMS encryption fails
     */
    public KmsSharedKeyEncryptionContext(KmsEncryptionConfig config) throws Exception {
        this.config = config;
        config.validate();

        // Initialize KMS client
        this.kmsClient = createKmsClient(config);

        // Generate DEK using AWS KMS (plaintext DEK never sent to AWS)
        GenerateDataKeyResponse response = generateDataKeyWithKms();

        // Extract plaintext DEK (generated by AWS, only travels FROM AWS to us)
        byte[] plaintextKeyBytes = response.plaintext().asByteArray();
        this.dataKey = new javax.crypto.spec.SecretKeySpec(plaintextKeyBytes, "AES");

        // Extract encrypted DEK (also generated by AWS)
        this.encryptedDataKey = response.ciphertextBlob().asByteArray();

        System.out.println("Generated shared DEK using KMS GenerateDataKey (plaintext DEK never sent over network)");
    }

    /**
     * Create KMS client
     */
    private KmsClient createKmsClient(KmsEncryptionConfig config) {
        var builder = KmsClient.builder();

        if (config.getAwsRegion() != null) {
            builder.region(Region.of(config.getAwsRegion()));
        }

        return builder.build();
    }

    /**
     * Generate data key using KMS GenerateDataKey API.
     *
     * This is more secure than generating locally and encrypting because:
     * - The plaintext DEK is generated inside AWS KMS
     * - Only travels FROM AWS to client (never TO AWS)
     * - Both plaintext and encrypted versions returned in one call
     */
    private GenerateDataKeyResponse generateDataKeyWithKms() throws Exception {
        // Determine key spec based on configured key size
        String keySpec = (config.getKeySize() == 128) ? "AES_128" : "AES_256";

        GenerateDataKeyRequest request = GenerateDataKeyRequest.builder()
            .keyId(config.getKmsKeyId())
            .keySpec(keySpec)
            .encryptionContext(config.getEncryptionContext())
            .build();

        return kmsClient.generateDataKey(request);
    }

    /**
     * Get the shared data encryption key
     */
    public SecretKey getDataKey() {
        if (closed) {
            throw new IllegalStateException("Encryption context has been closed");
        }
        return dataKey;
    }

    /**
     * Get the encrypted data key (base64-encoded for metadata)
     */
    public String getEncryptedDataKeyBase64() {
        if (closed) {
            throw new IllegalStateException("Encryption context has been closed");
        }
        return Base64.getEncoder().encodeToString(encryptedDataKey);
    }

    /**
     * Get the KMS encryption configuration
     */
    public KmsEncryptionConfig getConfig() {
        return config;
    }

    /**
     * Create an encrypting output stream using the shared DEK
     *
     * @param outputFile The file to write encrypted data to
     * @return A new KmsEnvelopeEncryptionOutputStream using the shared DEK
     * @throws Exception if stream creation fails
     */
    public KmsEnvelopeEncryptionOutputStream createEncryptingOutputStream(
            java.io.File outputFile) throws Exception {

        if (closed) {
            throw new IllegalStateException("Encryption context has been closed");
        }

        // Create output stream with shared DEK
        return new KmsEnvelopeEncryptionOutputStream(
            outputFile,
            this  // Pass the shared context
        );
    }

    @Override
    public void close() {
        if (!closed) {
            closed = true;
            if (kmsClient != null) {
                try {
                    kmsClient.close();
                } catch (Exception e) {
                    // Ignore cleanup errors
                }
            }
        }
    }
}
