name: Java Build Write Model
permissions:
  contents: read

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout project sources
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Run tests with Write Model
      run: ./gradlew build -Dparquet.carpet.useJavaRecord2WriteModel=true

