name: Documentation
on:
  push:
    branches:
      - master
    paths:
      - 'mkdocs/docs/**'
      - '.github/workflows/documentation.yml'

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip'

      - name: Install MkDocs Material
        run: |
          pip install mkdocs-material
          pip install mkdocs-material[imaging]

      - name: Build and Deploy Documentation
        working-directory: mkdocs
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          mkdocs gh-deploy --force